"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const PLUGIN_DIR = path.join(ROOT, "plugin");
const ENTRY_PATH = path.join(PLUGIN_DIR, "main.entry.js");
const OUTPUT_PATH = path.join(PLUGIN_DIR, "main.js");
const LOCAL_MODULES = [
  ["auth-session-adapter", path.join(PLUGIN_DIR, "auth-session-adapter.js")],
  ["pkce-auth", path.join(PLUGIN_DIR, "pkce-auth.js")],
  ["dashboard-pkce-host", path.join(PLUGIN_DIR, "dashboard-pkce-host.js")],
  ["provider-auth-navigation", path.join(PLUGIN_DIR, "provider-auth-navigation.js")],
  ["sync-protocol", path.join(PLUGIN_DIR, "sync-protocol.js")],
  ["translation-state", path.join(PLUGIN_DIR, "translation-state.js")],
  ["translation-view-bridge", path.join(PLUGIN_DIR, "translation-view-bridge.js")],
  ["host-window-runtime", path.join(PLUGIN_DIR, "host-window-runtime.js")],
  ["gm-element", path.join(PLUGIN_DIR, "gm-element.js")],
  ["gm-headers", path.join(PLUGIN_DIR, "gm-headers.js")],
  ["document-session", path.join(PLUGIN_DIR, "document-session.js")],
  ["document-workspace", path.join(PLUGIN_DIR, "document-workspace.js")],
  ["document-runtime", path.join(PLUGIN_DIR, "document-runtime.js")],
  ["userscript-compat", path.join(PLUGIN_DIR, "userscript-compat.js")],
  ["runtime-contract", path.join(PLUGIN_DIR, "runtime-contract.js")],
  ["runtime-installer", path.join(PLUGIN_DIR, "runtime-installer.js")],
];
const DASHBOARD_ENTRY_PATH = path.join(PLUGIN_DIR, "dashboard-preload.entry.js");
const DASHBOARD_OUTPUT_PATH = path.join(PLUGIN_DIR, "dashboard-preload.js");
const DASHBOARD_INLINE_MODULES = [
  ["sync-protocol", path.join(PLUGIN_DIR, "sync-protocol.js")],
  ["gm-element", path.join(PLUGIN_DIR, "gm-element.js")],
];

function read(filePath) {
  return fs.readFileSync(filePath, "utf8").replace(/^\uFEFF/, "");
}

function rewriteLocalRequires(source) {
  return source.replace(/\brequire\((['"])\.\/([^'"]+)\1\)/g, '__imtRequire("$2")');
}

function createBundle() {
  const factories = LOCAL_MODULES.map(([name, filePath]) => {
    const source = rewriteLocalRequires(read(filePath));
    return [
      "__imtFactories[" + JSON.stringify(name) + "] = function (module, exports, require) {",
      source,
      "};",
    ].join("\n");
  }).join("\n\n");

  const entry = rewriteLocalRequires(read(ENTRY_PATH));
  return [
    "/* Generated by scripts/build-plugin.js from plugin/main.entry.js. Do not edit this file directly. */",
    "/* Obsidian loads the plugin entry without a module-relative require; local runtime modules are embedded here. */",
    "var __imtFactories = Object.create(null);",
    "var __imtModuleCache = Object.create(null);",
    "function __imtRequire(name) {",
    "  var normalized = String(name).replace(/^\\.\\//, \"\").replace(/\\.js$/, \"\");",
    "  if (!Object.prototype.hasOwnProperty.call(__imtFactories, normalized)) return require(name);",
    "  if (!Object.prototype.hasOwnProperty.call(__imtModuleCache, normalized)) {",
    "    var module = { exports: {} };",
    "    __imtModuleCache[normalized] = module.exports;",
    "    __imtFactories[normalized](module, module.exports, __imtRequire);",
    "    __imtModuleCache[normalized] = module.exports;",
    "  }",
    "  return __imtModuleCache[normalized];",
    "}",
    "",
    factories,
    "",
    entry,
    "",
  ].join("\n");
}

function wrapCommonjsAsIife(source) {
  return [
    "(function () {",
    "var module = { exports: {} };",
    "var exports = module.exports;",
    source.replace(/^\uFEFF/, "").replace(/^["']use strict["'];\s*/, ""),
    "return module.exports;",
    "})()",
  ].join("\n");
}

function createDashboardPreload() {
  let output = read(DASHBOARD_ENTRY_PATH);
  for (const [name, filePath] of DASHBOARD_INLINE_MODULES) {
    const pattern = new RegExp("\\brequire\\((['\"])\\.\\/" + name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\1\\)", "g");
    const next = output.replace(pattern, function () { return wrapCommonjsAsIife(read(filePath)); });
    if (next === output) {
      throw new Error("dashboard-preload.entry.js must require ./" + name + " so the page bridge can be inlined");
    }
    output = next;
  }
  return [
    "/* Generated by scripts/build-plugin.js from plugin/dashboard-preload.entry.js. Do not edit this file directly. */",
    output,
  ].join("\n");
}

function writeIfChanged(filePath, output, checkOnly, label) {
  let current = null;
  try { current = fs.readFileSync(filePath, "utf8"); } catch (error) {
    if (!checkOnly && error.code !== "ENOENT") throw error;
  }
  if (checkOnly) {
    if (current !== output) {
      console.error(label + " is stale; run npm run build");
      process.exitCode = 1;
    }
    return;
  }
  fs.writeFileSync(filePath, output, "utf8");
  console.log("Built " + path.relative(ROOT, filePath));
}

function main() {
  const checkOnly = process.argv.includes("--check");
  writeIfChanged(OUTPUT_PATH, createBundle(), checkOnly, "plugin/main.js");
  writeIfChanged(DASHBOARD_OUTPUT_PATH, createDashboardPreload(), checkOnly, "plugin/dashboard-preload.js");
}

main();
