"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const PLUGIN_DIR = path.join(ROOT, "plugin");
const ENTRY_PATH = path.join(PLUGIN_DIR, "main.entry.js");
const OUTPUT_PATH = path.join(PLUGIN_DIR, "main.js");
const LOCAL_MODULES = [
  ["auth-session-adapter", path.join(PLUGIN_DIR, "auth-session-adapter.js")],
  ["pkce-auth", path.join(PLUGIN_DIR, "pkce-auth.js")],
  ["dashboard-pkce-host", path.join(PLUGIN_DIR, "dashboard-pkce-host.js")],
  ["provider-auth-navigation", path.join(PLUGIN_DIR, "provider-auth-navigation.js")],
  ["translation-view-bridge", path.join(PLUGIN_DIR, "translation-view-bridge.js")],
  ["host-window-runtime", path.join(PLUGIN_DIR, "host-window-runtime.js")],
  ["document-workspace", path.join(PLUGIN_DIR, "document-workspace.js")],
  ["document-runtime", path.join(PLUGIN_DIR, "document-runtime.js")],
  ["userscript-compat", path.join(PLUGIN_DIR, "userscript-compat.js")],
  ["runtime-contract", path.join(PLUGIN_DIR, "runtime-contract.js")],
  ["runtime-installer", path.join(PLUGIN_DIR, "runtime-installer.js")],
];

function read(filePath) {
  return fs.readFileSync(filePath, "utf8").replace(/^\uFEFF/, "");
}

function rewriteLocalRequires(source) {
  return source.replace(/\brequire\((['"])\.\/([^'"]+)\1\)/g, '__imtRequire("$2")');
}

function createBundle() {
  const factories = LOCAL_MODULES.map(([name, filePath]) => {
    const source = rewriteLocalRequires(read(filePath));
    return [
      "__imtFactories[" + JSON.stringify(name) + "] = function (module, exports, require) {",
      source,
      "};",
    ].join("\n");
  }).join("\n\n");

  const entry = rewriteLocalRequires(read(ENTRY_PATH));
  return [
    "/* Generated by scripts/build-plugin.js from plugin/main.entry.js. Do not edit this file directly. */",
    "/* Obsidian loads the plugin entry without a module-relative require; local runtime modules are embedded here. */",
    "var __imtFactories = Object.create(null);",
    "var __imtModuleCache = Object.create(null);",
    "function __imtRequire(name) {",
    "  var normalized = String(name).replace(/^\\.\\//, \"\").replace(/\\.js$/, \"\");",
    "  if (!Object.prototype.hasOwnProperty.call(__imtFactories, normalized)) return require(name);",
    "  if (!Object.prototype.hasOwnProperty.call(__imtModuleCache, normalized)) {",
    "    var module = { exports: {} };",
    "    __imtModuleCache[normalized] = module.exports;",
    "    __imtFactories[normalized](module, module.exports, __imtRequire);",
    "    __imtModuleCache[normalized] = module.exports;",
    "  }",
    "  return __imtModuleCache[normalized];",
    "}",
    "",
    factories,
    "",
    entry,
    "",
  ].join("\n");
}

function main() {
  const output = createBundle();
  const checkOnly = process.argv.includes("--check");
  let current = null;
  try { current = fs.readFileSync(OUTPUT_PATH, "utf8"); } catch (error) {
    if (!checkOnly && error.code !== "ENOENT") throw error;
  }

  if (checkOnly) {
    if (current !== output) {
      console.error("plugin/main.js is stale; run npm run build");
      process.exitCode = 1;
    }
    return;
  }

  fs.writeFileSync(OUTPUT_PATH, output, "utf8");
  console.log("Built " + path.relative(ROOT, OUTPUT_PATH));
}

main();
